name: Terraform Format
inputs:
  tf_actions_working_dir:
    required: true
    type: string
description: Terraform Format
runs:
  using: "composite"
  steps:
    - name: Terraform Format
      shell: bash
      working-directory: ${{ inputs.tf_actions_working_dir }}
      run: terraform fmt -diff -recursive #-check
