name: Terraform Plan --Destroy
inputs:
  environment:
    required: true
    type: string
  tf_actions_working_dir:
    required: true
    type: string
  params_dir:
    required: true
    type: string
description: Terraform Plan --Destroy
runs:
  using: "composite"
  steps:
    - name: Terraform Plan --Destroy
      shell: bash
      working-directory: ${{ inputs.tf_actions_working_dir }}
      run: |
        export exitcode=0
        terraform plan -destroy \
        -input=false \
        -detailed-exitcode \
        -var-file="${{ github.workspace }}/${{ inputs.params_dir }}/${{ inputs.environment }}-ado-variables.tfvars" \
        -out ${{ inputs.environment }}.plan.tfplan  || export exitcode=$?
        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        if [ $exitcode -eq 1 ]; then
          echo "Error: Terraform plan failed"
          exit 1
        elif [ $exitcode -eq 2 ]; then
          echo "Terraform plan was successful and has change"
        else
          echo "Terraform plan was successful"
          exit 0
        fi
