name: Download Terraform Plan
inputs:
  environment:
    required: true
    type: string
  tf_actions_working_dir:
    required: true
    type: string
description: Download Terraform Plan
runs:
  using: "composite"
  steps:
    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.environment }}${{ github.run_id }} #tfplan
        path: ${{ github.workspace }}/${{ inputs.tf_actions_working_dir }}

